### ISSUE TITLE
Node 12 in sonarsource/sonar-scanner-cli:latest (4.8)

### ISSUE THREAD

**Issue by splitmo** [SonarSource/sonar-scanner-cli-docker#182] opened 2023-04-24 14:43 UTC
Our gitlab sonar script is failing with:
`The version of node.js (12) you have used to run this analysis is deprecated and we stopped accepting it.`

We are using sonarsource/sonar-scanner-cli:latest, which at the moment points to build 4.8. 

I noticed the node version in this image on dockerhub indeed used node v12:
```
docker run -it --rm --entrypoint=node sonarsource/sonar-scanner-cli:4.8 -v
4.8: Pulling from sonarsource/sonar-scanner-cli
f56be85fc22e: Pull complete
06f8a6bde154: Pull complete
fe67d40b6a26: Pull complete
Digest: sha256:f41235dee4005b49837fff8fcacb11eee87c0e6994872596a921dd46c81d612f
Status: Downloaded newer image for sonarsource/sonar-scanner-cli:4.8
v12.22.9v18.14.2
```

whereas the older 4.7 uses node 18:

```docker run -it --rm --entrypoint=node sonarsource/sonar-scanner-cli:4.7.0 -v
4.7.0: Pulling from sonarsource/sonar-scanner-cli
c158987b0551: Pull complete
b552b7fc68ec: Pull complete
b40f79f04cea: Pull complete
Digest: sha256:f3d97bc61071007e83ae1253134606ff43b0902683da526a619e19999446882a
Status: Downloaded newer image for sonarsource/sonar-scanner-cli:4.7.0
v18.12.1```

**Comment by kisickilukasz** [comment] 2023-04-24 21:02
to add to that. We just updated our node to v 18.16.0 which is the latest LTS version but our CI fails with 
`
The engine "node" is incompatible with this module. Expected version "~18.16". Got "18.14.2"
`

**Comment by jCOTINEAU** [comment] 2023-05-05 14:58
Hello everyone, closing as this issue is a duplicate of #175.

To summarize, we released something that was not mean to, which has overridden the latest and 4.8 images.

Everything should be back to normal.

**Closed by jCOTINEAU** 2023-05-05 14:58 UTC
