### ISSUE TITLE
Even though we are using node 14 sonar saying Please update to at least node.js 14

### ISSUE THREAD

**Issue by jagadish10** [SonarSource/sonar-scanner-cli-docker#183] opened 2023-04-25 02:55 UTC
![image](https://user-images.githubusercontent.com/65954305/234162792-61dfaefe-afd5-4e96-be49-49a2f5ab49f5.png)
![image](https://user-images.githubusercontent.com/65954305/234163018-e5aa5e5f-007b-4fd5-b17e-5fff6916abe5.png)

Yesterday also we have faced same issue but it was resolved for some time.
I checked it in today morning it is causing same issue.

**Comment by jCOTINEAU** [comment] 2023-05-05 14:58
Hello everyone, closing as this issue is a duplicate of #175.

To summarize, we released something that was not meant to, which has overridden the latest and 4.8 images. 

Everything should be back to normal, as we reverted to the previous state

**Closed by jCOTINEAU** 2023-05-05 14:58 UTC
